FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ARG NUXT_APP_BASE_URL=""
ENV NUXT_APP_BASE_URL=${NUXT_APP_BASE_URL}

EXPOSE 2221

CMD ["npm", "run", "dev"]
